# Copyright 2025 Kristopher Rahim Afful-Brown. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

version: "3"

silent: true

tasks:
  default:
    desc: list tasks
    cmd: |
      task --list-all

  tidy:
    desc: tidy dependencies
    cmd: |
      go mod tidy

  test:
    desc: unit testing
    deps:
      - tidy
    cmd: |
      DEBUG=1 go test -count=1 -cover -timeout=60s {{.CLI_ARGS}}

  up:
    desc: run services
    deps:
      - down
      - dangle
      - tidy
    cmd: |
      docker compose up -d --build --force-recreate {{.CLI_ARGS}}

  down:
    desc: stop services
    cmd: |
      docker compose down --volumes {{.CLI_ARGS}}

  dangle:
    desc: remove dangling images
    cmd: |
      docker rmi $(docker images -f 'dangling=true' -q) || true

  prune:
    desc: prune containers
    cmd: |
      docker system prune -af

  logs:
    desc: run logs
    cmd: |
      docker compose logs -f {{.CLI_ARGS}}
